const cities = [
  { city: "london", postcode: "SW1A1AA" },
  { city: "birmingham", postcode: "B9 4AA" },
  { city: "manchester", postcode: "M1 1AJ" },
  { city: "leeds", postcode: "LS1 2SL" },
  { city: "liverpool", postcode: "L1 8JQ" },
  { city: "sheffield", postcode: "S1 1HA" },
  { city: "newcastle", postcode: "NE1 1AD" },
  { city: "bradford", postcode: "BD1 1JR" },
  { city: "bristol", postcode: "BS1 1BT" },
  { city: "sunderland", postcode: "SR1 1pS" },
  { city: "wolverhampton", postcode: "WV1 3HH" },
  { city: "crewe", postcode: "CW2 6HR" },
  { city: "nottingham", postcode: "NG1 2LH" },
  { city: "brighton", postcode: "BN1 1YR" },
  { city: "farnborough", postcode: "GU14 7SJ" },
  { city: "belfast", postcode: "BT1 1AA" },
  { city: "leicester", postcode: "LE1 1AA" },
  { city: "edinburgh", postcode: "EH3 9NB" },
  { city: "southampton", postcode: "SO15 1AL" },
  { city: "portsmouth", postcode: "PO1 1AQ" },
  { city: "derby", postcode: "DE1 1AA" },
  { city: "cardiff", postcode: "CF10 1EP" },
  { city: "swansea", postcode: "SA1 1SN" },
  { city: "preston", postcode: "PR1 7EA" },
  { city: "wakefield", postcode: "WF1 1PJ" },
  { city: "sunderland", postcode: "SR1 1PP" },
  { city: "hull", postcode: "HU1 3DX" },
  { city: "milton keynes", postcode: "MK9 2EA" },
  { city: "luton", postcode: " LU1 2LT" },
  { city: "northampton", postcode: "NN1 3EL" },
  { city: "peterborough", postcode: "PE1 1AB" },
  { city: "stoke", postcode: "ST4 6QS" },
  { city: "glasgow", postcode: "G1 3SQ" },
];

export default cities;
